spring:
  application:
    name: sebi-online-shop-app
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3309/sebi_OnlineShop_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.springframework.boot.autoconfigure.orm.jpa.CamelCaseToUnderscoresNamingStrategy
    show-sql: true

server:
  port: 8084
  error:
    include-stacktrace: never

application:
  jwt:
    secretKey: ${JWT_SECRET_KEY:asdasdasdasdasd123344asdasdasdasdasasd12321332sadasXYZ0123456789ABCDEF}
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 7

